// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cat_cafe.Repositories;

#nullable disable

namespace cat_cafe.Migrations
{
    [DbContext(typeof(CatCafeDbContext))]
    partial class CatCafeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("cat_cafe.Entities.Bar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("bars");
                });

            modelBuilder.Entity("cat_cafe.Entities.Cat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BarId");

                    b.ToTable("cats");
                });

            modelBuilder.Entity("cat_cafe.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("cat_cafe.Entities.Cat", b =>
                {
                    b.HasOne("cat_cafe.Entities.Bar", null)
                        .WithMany("cats")
                        .HasForeignKey("BarId");
                });

            modelBuilder.Entity("cat_cafe.Entities.Bar", b =>
                {
                    b.Navigation("cats");
                });
#pragma warning restore 612, 618
        }
    }
}
